### ISSUE TITLE
Please don't use `dap` namespace

### ISSUE THREAD

**Issue by mfussenegger** [hiberabyss/nvim-dbg#1]
I hope you don't mind the random input.

Given that there's a good chance this plugin is going to be used with nvim-dap I think it would be good if nvim-dbg would avoid using the `dap` namespace as it could lead to conflicts down the road.

I also saw that you're re-using the log module from dap. If your plan is to utilize nvim-dap as dependency I think there are some more opportunities. One example is the rpc functionality that handles the message parsing. An example how is here:

https://github.com/mfussenegger/nvim-dap/blob/618c068e4265e8e1f428b93868141ac92c7dde8e/tests/server.lua#L110-L118

Thanks for your efforts to improve the DAP ecosystem

**Comment by hiberabyss** [comment]
I will refactor the code, thanks for your suggestions. @mfussenegger

**Comment by hiberabyss** [comment]
Fixed with c19e88fa68d8cac2c3dd210dc16c9555e9df11b2
